// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkplaceMG.Entities;

#nullable disable

namespace WorkplaceMG.Migrations
{
    [DbContext(typeof(WorkplaceDbContext))]
    [Migration("20221129111313_seeder")]
    partial class seeder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WorkplaceMG.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Antony",
                            LastName = "Hopkins"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Tom",
                            LastName = "Hanks"
                        });
                });

            modelBuilder.Entity("WorkplaceMG.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("StockCount")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StockCount = 3,
                            Type = "Headphones"
                        },
                        new
                        {
                            Id = 2,
                            StockCount = 3,
                            Type = "Keyboard"
                        },
                        new
                        {
                            Id = 3,
                            StockCount = 3,
                            Type = "Mouse"
                        });
                });

            modelBuilder.Entity("WorkplaceMG.Entities.EquipmentForWorkplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdEquipment")
                        .HasColumnType("int");

                    b.Property<int>("IdWorkplace")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEquipment");

                    b.HasIndex("IdWorkplace");

                    b.ToTable("EquipmentForWorkplaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdEquipment = 1,
                            IdWorkplace = 1
                        },
                        new
                        {
                            Id = 2,
                            IdEquipment = 2,
                            IdWorkplace = 1
                        },
                        new
                        {
                            Id = 3,
                            IdEquipment = 1,
                            IdWorkplace = 2
                        },
                        new
                        {
                            Id = 4,
                            IdEquipment = 2,
                            IdWorkplace = 2
                        },
                        new
                        {
                            Id = 5,
                            IdEquipment = 1,
                            IdWorkplace = 3
                        },
                        new
                        {
                            Id = 6,
                            IdEquipment = 2,
                            IdWorkplace = 4
                        });
                });

            modelBuilder.Entity("WorkplaceMG.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int>("IdWorkplace")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("IdWorkplace");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("WorkplaceMG.Entities.Workplace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<int>("Room")
                        .HasColumnType("int");

                    b.Property<int>("Table")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Workplaces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Floor = 0,
                            Room = 1,
                            Table = 1
                        },
                        new
                        {
                            Id = 2,
                            Floor = 0,
                            Room = 1,
                            Table = 2
                        },
                        new
                        {
                            Id = 3,
                            Floor = 0,
                            Room = 2,
                            Table = 1
                        },
                        new
                        {
                            Id = 4,
                            Floor = 1,
                            Room = 1,
                            Table = 1
                        });
                });

            modelBuilder.Entity("WorkplaceMG.Entities.EquipmentForWorkplace", b =>
                {
                    b.HasOne("WorkplaceMG.Entities.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("IdEquipment")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkplaceMG.Entities.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("IdWorkplace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Workplace");
                });

            modelBuilder.Entity("WorkplaceMG.Entities.Reservation", b =>
                {
                    b.HasOne("WorkplaceMG.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkplaceMG.Entities.Workplace", "Workplace")
                        .WithMany()
                        .HasForeignKey("IdWorkplace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Workplace");
                });
#pragma warning restore 612, 618
        }
    }
}
